[package]
name = "omnia-verifier"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
chrono.workspace = true
omnia-core = { path = "../omnia-core" }
omnia-crypto = { path = "../omnia-crypto" }
serde_json.workspace = true
uuid.workspace = true
