apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yml
  - postgres.yml
  - api.yml
  - web.yml
  - ingress.yml

labels:
  - includeSelectors: true
    pairs:
      app.kubernetes.io/part-of: pactara
